apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  labels:
    app: java-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      containers:
      - name: java-microservice-container 
        image: 347516516956.dkr.ecr.us-east-2.amazonaws.com/flight-service:2.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-microservice-service
spec:
  #Creating a service of type load balancer. Load balancer gets created but takes time to reflect
  type: LoadBalancer 
  selector:
    app: java-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080