apiVersion: v1
kind: Service
metadata:
  name: flight-service
  namespace: flight-service-namespace
  labels:
    app: flight-app
spec:
  selector:
    app: flight-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: flight-service-namespace
  labels:
    app: flight-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight-app
  template:
    metadata:
      labels:
        app: flight-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: 347516516956.dkr.ecr.us-east-2.amazonaws.com/flight-service:latest
        ports:
        - containerPort: 80